apiVersion: v1
kind: Namespace
metadata:
  name: startech
--
apiVersion: apps/v1
kind: Deployment
metadata:
  name: startech-api
  namespace: startech
  labels:
    app: startech-api
spec:
  selector:
    matchLabels:
      app: startech-api
    replicas: 5
    revisionHistoryLimit: 5
    template:
      metadata:
        labels:
          app: "startech-api"
    spec:
      containers:
        - name: startech-api
          image: "olucaspio/startech:latest"
          imagePullPolicy: "Always"
          ports:
            - containerPort: 8080
              protocol: TCP
              name: startech-api
          resources:
            limits:
              cpu: 2
              memory: 128Mi
            requests:
              cpu: 300m
              memory: 128Mi
--
apiVersion: v1
kind: Service
metadata:
  name: startech-api
  namespace: startech
  labels:
    name: startech-api
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30131
  selector:
    name: startech-api